[build.environment]
  # bypass npm auto install
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  publish = "dist"
  command = "yarn--store=node_modules/.pnpm-store & yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
