// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBottomBar: typeof import('./components/AppBottomBar.vue')['default']
    AppHeaderBar: typeof import('./components/AppHeaderBar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LessonComponent: typeof import('./components/LessonComponent.vue')['default']
    QuestionComponent: typeof import('./components/QuestionComponent.vue')['default']
    QuizSessionComponent: typeof import('./components/QuizSessionComponent.vue')['default']
    QuizSessionResultComponent: typeof import('./components/QuizSessionResultComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserFooter: typeof import('./components/UserFooter.vue')['default']
    UserHeader: typeof import('./components/UserHeader.vue')['default']
  }
}
